### PR TITLE
Update readme (closes #144)

### LINKED ISSUE #144: Update readme.rst as other repositories
Update the readme.rst with the same layout as the other repositories ...

### PR DESCRIPTION
**Pull request by mohierf**

### CODE REVIEW

**Comment by algorys** [comment]
Hello thanks for PR, but you mix new class of Contact and Update README. 

Unfortunately, I've make big changes since this commit. And contact class use things I've removed :cry: 

I'll merge new host synthesis view in develop, so If you can redo PR ?

Thanks.

**Comment by mohierf** [comment]
Strange ... I had the idea that I branched from the most recent develop branch. Perharps I did not updated my repo before branching ... I will check that :wink:

**Comment by algorys** [comment]
Sorry @mohierf but can't accept this PR. 

`Contact` doesn't works and need many modifications. If you can redo PR only with README modifications ?

I'll manage `ContactView` ASAP.

Thanks

**Comment by mohierf** [comment]
I should not have pushed anything for Contact ... it was not my intent. I fix this ...

**Pull request merged**
